-- Integrity and clean-up, from the review before the API was built.
--
--   * Scheduling is gone for good. match.scheduled_at and match.court are
--     dropped, and a match waiting to be played is `open` rather than
--     `scheduled`.
--   * `rejected` is gone. A claim is replaced when its own side re-enters, or
--     settled by the coach; nobody rejects one. The confirm-flow columns go too.
--   * A claim carries the date its side says the match was played.
--   * Two cross-club references that row-level security could not catch are
--     now impossible: an entry is tied to its competition's club, and an
--     entry_member to its entry's club. Foreign-key checks ignore RLS, so
--     without these one club could write into another's division by naming ids.
--   * A match side must be an entry from the match's own competition, and an
--     entry cannot be drawn against itself.
--   * The ledger is consistent: a played match says how it ended and which
--     claim settled it, and that claim — like any acceptance — is about the
--     same match.
--   * The event log records the transaction that wrote each row, so a reader
--     can page it without skipping events that committed late. See 0011.
--
-- Generated by drizzle-kit from schema.ts, then edited by hand where marked
-- [hand]: views that depend on dropped columns are dropped first (0011 rebuilds
-- them), existing rows are carried across before the constraints that would
-- reject them, and unique constraints come before the foreign keys that need
-- them — drizzle-kit emits those the other way round.

-- [hand] These read match.scheduled_at or the old statuses; 0011 rebuilds them.
DROP VIEW IF EXISTS member_chase_list;
--> statement-breakpoint
DROP VIEW IF EXISTS outstanding_match;
--> statement-breakpoint
DROP VIEW IF EXISTS entry_progress;
--> statement-breakpoint
DROP VIEW IF EXISTS competition_progress;
--> statement-breakpoint
DROP VIEW IF EXISTS division_progress;
--> statement-breakpoint

-- ── scheduling out, `open` in ───────────────────────────────────────────────
ALTER TABLE "match" DROP CONSTRAINT "match_status_ck";
--> statement-breakpoint
-- [hand]
UPDATE "match" SET status = 'open' WHERE status = 'scheduled';
--> statement-breakpoint
ALTER TABLE "match" ALTER COLUMN "status" SET DEFAULT 'open';
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_status_ck" CHECK (status in ('open', 'reported', 'played', 'disputed', 'void'));
--> statement-breakpoint
DROP INDEX "match_outstanding_ix";
--> statement-breakpoint
CREATE INDEX "match_outstanding_ix" ON "match" USING btree ("competition_id") WHERE "match"."status" in ('open', 'reported', 'disputed');
--> statement-breakpoint
ALTER TABLE "match" DROP COLUMN "scheduled_at";
--> statement-breakpoint
ALTER TABLE "match" DROP COLUMN "court";
--> statement-breakpoint

-- ── claims: no `rejected`, a date, and a sideless claim never waits ─────────
ALTER TABLE "result_submission" DROP CONSTRAINT "result_submission_state_ck";
--> statement-breakpoint
-- [hand]
UPDATE "result_submission" SET state = 'superseded' WHERE state = 'rejected';
--> statement-breakpoint
ALTER TABLE "result_submission" ADD CONSTRAINT "result_submission_state_ck" CHECK (state in ('pending', 'confirmed', 'superseded'));
--> statement-breakpoint
ALTER TABLE "result_submission" DROP CONSTRAINT "result_submission_confirmer_fk";
--> statement-breakpoint
ALTER TABLE "result_submission" DROP COLUMN "confirmed_by_member_id";
--> statement-breakpoint
ALTER TABLE "result_submission" DROP COLUMN "rejected_at";
--> statement-breakpoint
ALTER TABLE "result_submission" DROP COLUMN "reject_reason";
--> statement-breakpoint
ALTER TABLE "result_submission" ADD COLUMN "played_on" date;
--> statement-breakpoint
ALTER TABLE "result_submission" ADD CONSTRAINT "result_submission_sideless_ck" CHECK (side_index is not null or state <> 'pending');
--> statement-breakpoint
ALTER TABLE "result_submission" ADD CONSTRAINT "result_submission_accepts_side_ck" CHECK (accepts_submission_id is null or side_index is not null);
--> statement-breakpoint
ALTER TABLE "result_submission" ADD CONSTRAINT "result_submission_stopped_side_ck" CHECK ((retired_side is not null) = coalesce(outcome in ('retired', 'walkover', 'conceded'), false));
--> statement-breakpoint
ALTER TABLE "result_submission" ADD CONSTRAINT "result_submission_score_ck" CHECK ((score is not null) = coalesce(outcome in ('completed', 'retired'), false));
--> statement-breakpoint

-- ── acceptances and the ledger point at claims on the same match ────────────
ALTER TABLE "result_submission" ADD CONSTRAINT "result_submission_id_match_uq" UNIQUE("id","match_id");
--> statement-breakpoint
ALTER TABLE "result_submission" DROP CONSTRAINT "result_submission_accepts_fk";
--> statement-breakpoint
ALTER TABLE "result_submission" ADD CONSTRAINT "result_submission_accepts_fk" FOREIGN KEY ("accepts_submission_id","match_id") REFERENCES "public"."result_submission"("id","match_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
-- [hand] Results entered before this never set accepted_submission_id. Point
-- each at its most recent confirmed claim; a played match with none at all
-- has no claim behind it, and match_played_claim_ck below will say so.
UPDATE "match" m SET accepted_submission_id = (
  SELECT rs.id FROM "result_submission" rs
   WHERE rs.match_id = m.id AND rs.state = 'confirmed'
   ORDER BY rs.confirmed_at DESC NULLS LAST, rs.id DESC
   LIMIT 1)
 WHERE m.status = 'played' AND m.accepted_submission_id IS NULL;
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_accepted_submission_fk" FOREIGN KEY ("accepted_submission_id","id") REFERENCES "public"."result_submission"("id","match_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_played_outcome_ck" CHECK ((status = 'played') = (outcome is not null));
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_played_claim_ck" CHECK ((status = 'played') = (accepted_submission_id is not null));
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_winner_ck" CHECK ((winning_side is not null) = (outcome is not null and outcome <> 'unplayed'));
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_winner_not_retired_ck" CHECK (winning_side <> retired_side);
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_stopped_side_ck" CHECK ((retired_side is not null) = coalesce(outcome in ('retired', 'walkover', 'conceded'), false));
--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_score_ck" CHECK ((score is not null) = coalesce(outcome in ('completed', 'retired'), false));
--> statement-breakpoint

-- ── tenancy: the two references RLS could not see ───────────────────────────
ALTER TABLE "entry" ADD CONSTRAINT "entry_competition_fk" FOREIGN KEY ("competition_id","club_id") REFERENCES "public"."competition"("id","club_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "entry_member" ADD CONSTRAINT "entry_member_entry_club_fk" FOREIGN KEY ("entry_id","club_id") REFERENCES "public"."entry"("id","club_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint

-- ── match sides come from the match's own competition ───────────────────────
ALTER TABLE "match" ADD CONSTRAINT "match_id_competition_uq" UNIQUE("id","competition_id");
--> statement-breakpoint
-- [hand] Added nullable, filled from the match, then made required.
ALTER TABLE "match_side" ADD COLUMN "competition_id" uuid;
--> statement-breakpoint
UPDATE "match_side" ms SET competition_id = m.competition_id FROM "match" m WHERE m.id = ms.match_id;
--> statement-breakpoint
ALTER TABLE "match_side" ALTER COLUMN "competition_id" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "match_side" ADD CONSTRAINT "match_side_competition_fk" FOREIGN KEY ("match_id","competition_id") REFERENCES "public"."match"("id","competition_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "match_side" DROP CONSTRAINT "match_side_entry_fk";
--> statement-breakpoint
ALTER TABLE "match_side" ADD CONSTRAINT "match_side_entry_fk" FOREIGN KEY ("entry_id","competition_id") REFERENCES "public"."entry"("id","competition_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "match_side" ADD CONSTRAINT "match_side_match_entry_uq" UNIQUE("match_id","entry_id");
--> statement-breakpoint

-- ── event log: which transaction wrote each row ─────────────────────────────
-- Existing rows all take this migration's transaction id, which keeps them in
-- id order ahead of anything written later.
ALTER TABLE "event" ADD COLUMN "tx_id" "xid8" DEFAULT pg_current_xact_id() NOT NULL;
--> statement-breakpoint
CREATE INDEX "event_feed_ix" ON "event" USING btree ("club_id","tx_id","id");
