-- A match can no longer be `void`.
--
-- Everything void was for is covered another way: a wrong score is corrected
-- by a coach entry, a match that never happened is `unplayed`, a side at fault
-- concedes a walkover, a withdrawal follows the competition's rules when
-- standings are read, and an entry made by mistake is deleted with its
-- untouched fixtures. What was left — striking a result out of the ledger with
-- no claim to show for it — is the one thing the ledger should not allow.
-- (rules.withdrawal.playedMatches = 'void' is a different thing, and stays.)
--
-- Generated by drizzle-kit from schema.ts, then edited by hand where marked
-- [hand]. A database holding a void match refuses this migration rather than
-- guess what that match should become.

ALTER TABLE "match" DROP CONSTRAINT "match_status_ck";--> statement-breakpoint
ALTER TABLE "match" ADD CONSTRAINT "match_status_ck" CHECK (status in ('open', 'reported', 'played', 'disputed'));
--> statement-breakpoint

-- [hand] The two progress views no longer need to leave void matches out.
-- CREATE OR REPLACE keeps each view, and so the comments on its columns.
CREATE OR REPLACE VIEW division_progress WITH (security_invoker = true) AS
SELECT
  d.club_id,
  d.competition_id,
  c.name                        AS competition_name,
  d.id                          AS division_id,
  d.ordinal                     AS division_ordinal,
  d.name                        AS division_name,
  s.id                          AS season_id,
  s.name                        AS season_name,
  s.results_deadline_at,
  deuceleague_days_until(s.results_deadline_at, cl.timezone) AS days_remaining,
  (SELECT count(*) FROM entry e
    WHERE e.division_id = d.id AND e.state = 'active')  AS active_entries,
  mm.matches,
  mm.played,
  mm.outstanding,
  mm.reported,
  mm.disputed,
  CASE WHEN mm.matches = 0 THEN NULL
       ELSE round(100.0 * mm.played / mm.matches, 1) END AS percent_played
FROM division d
JOIN competition c ON c.id = d.competition_id
JOIN season s      ON s.id = c.season_id
JOIN club cl       ON cl.id = d.club_id
CROSS JOIN LATERAL (
  SELECT
    count(*)                                                                AS matches,
    count(*) FILTER (WHERE m.status = 'played')                             AS played,
    -- Everything not yet in the ledger.
    count(*) FILTER (WHERE m.status IN ('open', 'reported', 'disputed'))    AS outstanding,
    -- One side has claimed a score and is waiting on the other.
    count(*) FILTER (WHERE m.status = 'reported')                           AS reported,
    -- Both have claimed and they differ. Either can re-enter; the coach can settle it.
    count(*) FILTER (WHERE m.status = 'disputed')                           AS disputed
  FROM match m
  WHERE m.division_id = d.id
) mm;
--> statement-breakpoint

-- [hand]
CREATE OR REPLACE VIEW entry_progress WITH (security_invoker = true) AS
SELECT
  el.club_id, el.competition_id, el.division_id, el.entry_id,
  el.label, el.member_ids, el.state,
  p.matches, p.played, p.outstanding
FROM entry_label el
CROSS JOIN LATERAL (
  SELECT
    count(*)                                                             AS matches,
    count(*) FILTER (WHERE m.status = 'played')                          AS played,
    count(*) FILTER (WHERE m.status IN ('open', 'reported', 'disputed')) AS outstanding
  FROM match_side ms
  JOIN match m ON m.id = ms.match_id
  WHERE ms.entry_id = el.entry_id
) p;
--> statement-breakpoint

-- [hand] Descriptions that mentioned void.
COMMENT ON COLUMN "match"."status" IS 'This match''s lifecycle: open (nobody has reported), reported (one side has claimed a score), played (both sides agree, or the coach decided), or disputed (both sides claimed and differ). Nothing moves to played on a timer — see docs/DATA-MODEL.md § Results.';
--> statement-breakpoint
COMMENT ON COLUMN "division_progress"."matches" IS 'How many matches this division has in total.';
--> statement-breakpoint
COMMENT ON COLUMN "entry_progress"."matches" IS 'How many matches this entry has in total.';
