-- Stand-ins are not recorded.
--
-- match_participant was to hold who was actually on court, so a stand-in
-- partner would not disturb a pair's record. Nothing ever wrote to it, and a
-- result counts for the entry drawn to play either way, so it goes. Its
-- row-level security policy and comments go with it.
--
-- Generated by drizzle-kit from schema.ts, then edited by hand where marked
-- [hand]: without CASCADE, so anything that had come to depend on the table
-- stops this migration rather than disappearing with it.

-- [hand]
DROP TABLE "match_participant";
