-- A competition is visible to `members` or `private`; `public` is gone.
--
-- Nothing is readable without a credential (0015), so `public` could only ever
-- have meant the same as `members`. What is left: `members` for every member of
-- the club who signs in, `private` for the coach's own credentials only, never
-- a player's login.
--
-- Generated by drizzle-kit from schema.ts, then edited by hand where marked
-- [hand].

ALTER TABLE "competition" DROP CONSTRAINT "competition_visibility_ck";--> statement-breakpoint
-- [hand] A competition marked public was already shown exactly as members'.
UPDATE "competition" SET "visibility" = 'members' WHERE "visibility" = 'public';--> statement-breakpoint
ALTER TABLE "competition" ADD CONSTRAINT "competition_visibility_ck" CHECK (visibility in ('members', 'private'));
--> statement-breakpoint

-- [hand]
COMMENT ON COLUMN "competition"."visibility" IS 'Who may see this competition, among those who have signed in: members (every member of the club) or private (the coach''s own credentials only, never a player''s login). Nothing is readable without a credential.';
