-- Player logins: a login link, and the session it is exchanged for.
--
-- An access grant is now one of two kinds. A login link works once and
-- expires within minutes, so it must have an expiry. A session has none: a
-- player signs in once per phone, because a league is used a few times a month
-- and a login screen each time is how players drift away. It ends when it is
-- signed out, or when the member is removed.
--
-- Revoking a grant deletes it. A link is deleted when it is exchanged, which
-- is also what makes it work only once: two exchanges racing for the same link
-- both try to delete it, and only one finds it. So used_at goes; nothing is
-- kept that no longer works, and there is nothing personal left behind.
--
-- Generated by drizzle-kit from schema.ts, then edited by hand where marked
-- [hand].

-- [hand] The resolver reads used_at and returns it, so it goes first, and comes
-- back below returning the grant's kind instead.
DROP FUNCTION deuceleague_resolve_access_grant(text);
--> statement-breakpoint
-- [hand] Links work once. Until now that was used_at; from now on a used link
-- is simply deleted, so one already used goes now.
DELETE FROM "access_grant" WHERE "used_at" IS NOT NULL;
--> statement-breakpoint
ALTER TABLE "access_grant" ALTER COLUMN "expires_at" DROP NOT NULL;--> statement-breakpoint
-- [hand] drizzle-kit adds a NOT NULL column with nothing in it. Nothing issued
-- grants before this, but any made by hand all expire, so they are links.
ALTER TABLE "access_grant" ADD COLUMN "kind" text NOT NULL DEFAULT 'login_link';--> statement-breakpoint
ALTER TABLE "access_grant" ALTER COLUMN "kind" DROP DEFAULT;--> statement-breakpoint
CREATE INDEX "access_grant_member_ix" ON "access_grant" USING btree ("member_id");--> statement-breakpoint
ALTER TABLE "access_grant" ADD CONSTRAINT "access_grant_kind_ck" CHECK (kind in ('login_link', 'session'));--> statement-breakpoint
ALTER TABLE "access_grant" ADD CONSTRAINT "access_grant_link_expires_ck" CHECK (kind <> 'login_link' or expires_at is not null);--> statement-breakpoint
ALTER TABLE "access_grant" DROP COLUMN "used_at";
--> statement-breakpoint

-- [hand] A live grant — a link that has not expired, or a session — for a
-- member who has not been removed. The API checks its kind: a link is good
-- only for being exchanged, and is deleted when it is.
CREATE FUNCTION deuceleague_resolve_access_grant(token_hash text)
  RETURNS TABLE (club_id uuid, access_grant_id uuid, member_id uuid, kind text, scopes text[])
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp
  AS $$
    SELECT g.club_id, g.id, g.member_id, g.kind, g.scopes
    FROM access_grant g
    JOIN member mb ON mb.id = g.member_id AND mb.deleted_at IS NULL
    WHERE g.token_hash = deuceleague_resolve_access_grant.token_hash
      AND (g.expires_at IS NULL OR g.expires_at > now())
  $$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION deuceleague_resolve_access_grant(text) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION deuceleague_resolve_access_grant(text) TO deuceleague_app;
--> statement-breakpoint

-- [hand]
COMMENT ON FUNCTION deuceleague_resolve_access_grant(text) IS 'Looks up a live access grant — a login link that has not expired, or a session — for a member who has not been removed, by the SHA-256 hash of its token. Returns its kind, so the API can accept a link only for exchanging it. SECURITY DEFINER, for the same reason as deuceleague_resolve_api_key().';
--> statement-breakpoint
COMMENT ON TABLE "access_grant" IS 'A player''s way in: a one-time login link, or the session it is exchanged for. Each speaks for one member. Revoking one deletes it, so every row still works or has expired.';
--> statement-breakpoint
COMMENT ON COLUMN "access_grant"."kind" IS 'login_link: works once, to be exchanged for a session, and expires within minutes. session: what a signed-in player presents; it does not expire, and ends when it is signed out or the member is removed.';
--> statement-breakpoint
COMMENT ON COLUMN "access_grant"."token_hash" IS 'SHA-256 hash of the token. The token itself is shown once — in the login link, or to the website holding the session — and only this hash is stored.';
--> statement-breakpoint
COMMENT ON COLUMN "access_grant"."scopes" IS 'Which scopes this grant carries: a player''s, league:read and results:write. The API narrows them further, to competitions open to members and the player''s own side.';
--> statement-breakpoint
COMMENT ON COLUMN "access_grant"."expires_at" IS 'When this grant stops working. Always set for a login link; null for a session, which lasts until it is signed out.';
