-- A player can opt out of the next competition.
--
-- The one thing a player says about next season, recorded on the entry they
-- hold now: filling next season's draft leaves them out, with a sentence
-- saying why, and the coach can add them back if they change their mind. It
-- says nothing about the competition it sits in — they play their remaining
-- matches as usual.
--
-- Generated by drizzle-kit from schema.ts, with the comment added by hand.

ALTER TABLE "entry" ADD COLUMN "opted_out_at" timestamp with time zone;--> statement-breakpoint

COMMENT ON COLUMN "entry"."opted_out_at" IS 'When the player said they are not playing in the next competition — or when the coach recorded it for them. Null unless they said so; clearing it puts them back in the reckoning. It does not affect this competition: their outstanding matches still stand.';
